# Generated by Django 3.2.7 on 2022-02-07 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.tenantawaremodel')),
                ('name', models.CharField(max_length=100)),
                ('describtion', models.CharField(blank=True, max_length=255, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            bases=('tenants.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.tenantawaremodel')),
                ('name', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest', to='cuisine.restaurant')),
            ],
            bases=('tenants.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.tenantawaremodel')),
                ('menu_item', models.CharField(max_length=255)),
                ('Ingredients', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('menus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='cuisine.menu')),
            ],
            bases=('tenants.tenantawaremodel',),
        ),
    ]
