# Generated by Django 3.2.7 on 2022-02-07 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='menus',
        ),
        migrations.AddField(
            model_name='item',
            name='menues',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menues', to='cuisine.menu'),
        ),
    ]
