# Generated by Django 3.2.7 on 2022-02-07 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0002_auto_20220207_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='menues',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuisine.menu'),
        ),
    ]
