# Generated by Django 3.2.7 on 2022-02-07 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0003_alter_item_menues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='menues',
        ),
        migrations.AddField(
            model_name='item',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='cuisine.menu'),
        ),
    ]
