# Generated by Django 3.2.7 on 2022-02-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0004_auto_20220207_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='component',
            new_name='comp',
        ),
    ]
